config/routes.rb
Rails.application.routes.draw do
  
  

  
  get 'advices/leave'
  get 'advices/statistics', to: 'advices#advice_statistics'
  get 'intro', to: 'advices#intro'
  resources :advices
  
  get 'advices/first'
  get 'advices/second'

  resources :surveys
  resources :patients do 
    resource :profile
  end  

  
  devise_for :members, :controllers => {:registrations => "members"}
  resources :members 
  
  get 'questions/index'
  

  

  get 'users/index'

  get 'questions/notes'
  
  get 'statistics/list_indicator'
  get 'statistics/adverse_reactions'
  get 'statistics/side_effects'
  get 'statistics/drugs'
  get 'statistics/aggregated_drugs'
  post 'statistics/aggregated_drugs'
  
  resources :users
  resources :questions
  
  resources :statistics

  get 'pages/home'
  root 'pages#home'  

end

app/models/question.rb
class Question < ActiveRecord::Base
    # has_many :options
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    include QuestionsHelper       
    
    
  def index

    @questions = Question.all
    qids = @questions.map{|q| q.qid}
    @num_of_questions = qids.uniq.length
    #binding.pry
  end
  
  def show
     @subq_mapping = {1 => "A", 2 => "B", 3 => "C", 4 => "D"} 
     @first_question = 1
     @last_question = 18
     question_idx = [2, 3, 4, 5,  6, 7]
     @subquestion_idx = [4, 5, 7, 11]
     qone = get_reference_question(params[:id].to_i)
     #binding.pry
     #logger.warn "qone: #{qone}"
     

     #parent_one = 1
     
     @question = Question.where("qid = ? AND subid = ?", params[:id], 0)[0]
     @question_number = Question.where(subid: 0).length
     opt = QuestionOption.where("qid = ? AND subid = ?", params[:id], 0)
     @options = opt.map{|o| o.odescription}
     
    # counter = []
     total = []
     
     Answer.where("qid = ? and  subid = ?", params[:id], 0).each do |a|
         if question_idx.include? a.qid
             #parent_ans = Answer.where(qid: parent_one, subid: 0, uid: a.uid)[0].answer
             parent_ans = qone[a.uid]
              #logger.debug "parent answer (controller): #{parent_ans}"
                if parent_ans =~ /no\s*/i || parent_ans.nil?
                     #logger.debug "inside if"
                     next
                end
                #binding.pry
         end
          total << a.answer

    end
      
       #logger.debug "Total: #{total}"
       @counts = Hash.new 0
       @count_drugs = Hash.new 0
       @count_categories = Hash.new 0
       #resp_vect = []

       logger.debug "total length: #{total.length}"
       total.each do |resp|
           resp = resp.downcase unless resp.nil?
           resp.nil? ? resp = "nessuna risposta" : resp.strip!
           #binding.pry
           #logger.debug("resp: #{resp}")
           if resp =~ /^farmaco/
              #logger.warn "resp: #{resp}"
                resp_vect = resp.split(",").map{|w| w.downcase}
                #logger.debug "Resp vect: #{resp_vect}"
                drug = resp_vect[0].gsub("farmaco: ", "").strip
                #logger.info "Drug: #{drug}"
                category = resp_vect[1].gsub("categoria: ", "").strip
                #logger.info "Category: #{category}"
              unless drug.nil? || drug == ""
                    drug = sanitize_drug_name(drug)
                    @count_drugs[drug] += 1
              end   
              unless category.nil? || category == ""
                    @count_categories[category] += 1
              end
           end
           
           @counts[resp] += 1
        end
    #binding.pry 
    logger.debug "Counts: #{@counts}"
     #binding.pry
     #binding.pry
     @counts.slice!("sì", "no") if [5, 6, 7].include? @question.qid
     
     
     @count_drugs = filter_counts(@count_drugs, 1)
     ###here we sort by value in descending order
     @count_drugs = (@count_drugs.sort_by{|drug, count| -count}).to_h
     
     @count_categories = filter_counts(@count_categories, 1)
     @count_categories = (@count_categories.sort_by{|category, count| -count}).to_h
     #binding.pry
     #logger.debug "count_categories: #{@count_categories}"
     @subquestions = Question.where("qid = ? AND subid <> 0", params[:id])
     @suboptions = QuestionOption.where("qid = ? AND subid <> 0", params[:id])
     
     
  end
  
    def edit
        id = params[:id]
        @question = Question.where(qid: id)[0]
    end    
  
    def notes
      @answers = Answer.all.order(:qid)

    end      

  
  
  
  private
  def get_reference_question(qid)
        question_id = case qid
        when 1..7 then 1
        when 9..10 then 9
        end    
        #logger.warn "question_id: #{question_id}"
        q = Answer.where(qid: question_id, subid: 0)
        h = Hash.new 0
        q.each do |a|
            h[a.uid] = a.answer
        end
        return h
  end
  
  def filter_counts(counts, threshold = 1)
      w = counts.select{|k, v| v > threshold}
  end
  
  
  
  
  
  
  
  
  
end

app/helpers/questions_helper.rb
module QuestionsHelper
    
    

        
    
    QUESTION_IDX = [1,2,3,4,5,6,7]
   
    def sub_count(qid, subid)
        total = []
        qone = get_reference_question(qid)
        
        parent_one = 1
        Answer.where("qid = ? and  subid = ?", qid, subid).each do |a|
            if QUESTION_IDX.include? qid
                #parent_ans = Answer.where(qid: parent_one, subid: 0, uid: a.uid)[0].answer
                parent_ans = qone[a.uid]
                #logger.debug "parent answer: #{parent_ans}"
                if parent_ans =~ /no/ || parent_ans.nil?
                     #logger.debug "inside if"
                     next
                end

            end
            total << a.answer           
        end
        #logger.debug "total length: #{total.length}"
        counts = Hash.new 0
        count_drugs = Hash.new 0
        count_categories = Hash.new 0
        
        
        total.each do |resp|
            resp = resp.downcase unless resp.nil?
            resp.nil? ? resp = "nessuna risposta" : resp.strip!
            if resp =~ /^farmaco/
                resp_vect = resp.split(",").map{|w| w.downcase}
                drug = resp_vect[0].gsub("farmaco: ", "").strip
                category = resp_vect[1].gsub("categoria: ", "").strip
                #binding.pry
              unless drug.nil? || drug == "" || drug == "-"
                    drug = sanitize_drug_name(drug)
                    count_drugs[drug] += 1
              end   
              unless category.nil? || category == "" || category == "-"
                    count_categories[category] += 1
              end
            end

            counts[resp] += 1
        end
        
        qoptions = QuestionOption.where(qid: qid, subid: subid).map{|opt| opt.odescription.strip}
        count_keys = counts.keys
        
        qoptions.each do |opt|
            next if count_keys.include? opt
            counts[opt] = 0
        end    
                
        
        counts.except!("nessuna risposta") if (qid == 11 && subid == 2) || (qid == 6 && subid == 1)
        #binding.pry
        count_drugs = filter_counts(count_drugs, 0)
        ##here we sort by value in descending order
        count_drugs = (count_drugs.sort_by{|drug, count| -count}).to_h
        count_categories = filter_counts(count_categories, 0)
        count_categories = (count_categories.sort_by{|category, count| -count}).to_h
        return counts, count_drugs, count_categories
    end  
    
    
  def get_reference_question(qid)
        question_id = case qid
        when 1..7 then 1
        when 9..10 then 9
        end    
        
        q = Answer.where(qid: question_id, subid: 0)
        h = Hash.new 0
        q.each do |a|
            h[a.uid] = a.answer
        end
        return h
  end 
  
  
  def filter_counts(counts, threshold = 1)
            w = counts.select{|k, v| v > threshold}
  end
  
  
  
  def get_prescriber(qid, subid)
    if qid != 8
        return
    end
    total = []
    total = Answer.where(qid: 8, subid: 1).map {|a| a.answer}
    
    count_prescriber = Hash.new 0
    count_changer = Hash.new 0
    count = Hash.new 0
    
    total.each do |resp|
        next if resp.nil? || resp == ""
        resp_vect = resp.split(",")
        logger.warn "resp_vect: #{resp_vect}"
        
        prescriber = resp_vect[0].strip.downcase unless resp_vect[0].nil?
        changer = resp_vect[1].strip.downcase unless resp_vect[1].nil?
        
        count_prescriber[prescriber] += 1
        count_changer[changer] += 1
        count[resp.downcase] += 1
   
    end
    
    count_prescriber = filter_counts(count_prescriber)
    count_changer = filter_counts(count_changer)
    #binding.pry
    return count_prescriber, count_changer, count

  end 
  
  def get_suggestions(qid)
      answers = Answer.where(qid: 18).map{|a| a.answer}
      answers = answers.reject{|a| a == ""}
  end
  
  def sanitize_drug_name(drug)
     wrong_to_corr = {"chetoprofene" => "ketoprofene", "paracetamolo generico" => "paracetamolo", 
     "enn" => "en", "efferalgan gusto pompelmo" => "efferalgan", "loperamide hexal" => "loperamide", 
     "ibuprofene generico" => "ibuprofene","atovarstatina" => "atorvastatina", "moment act" => "momentact"}
     
     if wrong_to_corr.keys.include? drug
         drug = wrong_to_corr[drug]
     end     
     drug    
  end    
    
    
end

app/views/questions/_form.html.erb
<%= form_for :question do |f| %>
    <% if @question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
  
        <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field form-group">
        <%= f.label :qid, "question id".upcase %><br/>
        <%= f.text_field :qid, autofocus: true, value: @question.qid, class: 'form-control', readonly: true %>
    </div><br/>
    
     <div class="field form-group">
        <%= f.label "question text" %><br/>
        <%= f.text_area :qtext, value: @question.qtext, autofocus: true, class: 'form-control', include_blank: true %>
    </div><br/>
 
  <div class="actions form-group">
    <%= f.submit "Registra", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<% @question %> 
<%= render 'form' %>

<%#= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Quesiti</h1>
        <!--<p>Questions to evaluate the side effects of drugs used in Sardinia</p>-->
        <ul class="list-unstyled">
 
            <% 1.upto(@num_of_questions).each do |idx| %>
                 <li>
                    <div class="well row <%=cycle('q-bg', '')%>">
                         <div class="col-md-2 text-center">
                                <i class="fa fa-question-circle fa-4x" aria-hidden="true"></i>
                                <!--<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>-->
                         </div>
                         <div class="col-md-4">
                             <h2><%= link_to "Domanda #{idx}", question_path(idx) %></h2>
                             
                         </div>
                        
                   
                        <div class="btn-group q-btn">
                                  <button type="button" class="btn btn-success">Mostra</button>
                                  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                  </button>
                                  <ul class="dropdown-menu">
                                    <li><%= link_to "show question", question_path(idx) %></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                  </ul>
                          </div>
                      
                        <div class="btn-group q-btn">
                                  <button type="button" class="btn btn-info">Modifica</button>
                                  <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                  </button>
                                  <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                  </ul>
                          </div>
                          
                         <div class="btn-group q-btn">
                                  <button type="button" class="btn btn-danger">Cancella</button>
                                  <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="caret"></span>
                                    <span class="sr-only">Toggle Dropdown</span>
                                  </button>
                                  <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                  </ul>
                          </div>
                
                        
                    </div>
                </li>
            <% end %>
        </ul>    
        
    </div>
    
    
    
    
    
</div>

app/views/questions/notes.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Answers Notes</h1>
        <p>Notes to the answers</p>
       <table class="table table-bordered table-hover">
        <tbody>
           <tr>
               <th>QUESTION ID</th>
               <th>QUESTION</th>
               <th>NOTE</th>
           </tr><br/>
           <tr>
               <th></th>
               <th></th>
           </tr>               
          <% @answers.each do |a| %>
                <% unless a.note.nil? || a.note == "" %>              
                 <tr class="<%= cycle('active', 'success', 'warning', 'danger', 'info')%>">

                   <td><%= a.qid %></td>
                   <td><%= Question.where("qid = ?", a.qid)[0].qtext %></td>
                   <td>
                     <%= a.note %>   
                   </td>
                </tr>
                <% end %>
          <% end %>
        </tbody>  
        </table>
    </div>
</div>    

app/views/questions/show.html.erb
<%# require 'pry' %>
<div class="row">
  
    <div class="col-md-8">
        <h1 class="h1 question"><%="Domanda #{@question.qid}"%>
        <div id="q-arrows">
            <%= link_to questions_path do %>
                <i class="fa fa-list" aria-hidden="true"></i>
            <% end %>    
            
            <%= link_to question_path(@first_question) do %>
                <i class="fa fa-angle-double-left" aria-hidden="true"></i>
            <% end %>
            
            <% previous_question = @question.qid == 1 ? 1 : @question.qid - 1 %>
            <%= link_to question_path(previous_question) do %>
                <i class="fa fa-arrow-circle-left" aria-hidden="true"></i>
            <% end %>
            <% next_question = @question.qid == @question_number ? @question_number : @question.qid + 1 %>
            <%= link_to question_path(next_question) do %>
                <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
            <% end %>
            
            <%= link_to question_path(@last_question) do %>
                <i class="fa fa-angle-double-right" aria-hidden="true"></i>
            <% end %>
            
        </div>

        </h1>
        <div class="well question-block question-description">
            <h3>Descrizione</h3>
            <%= @question.qtext %>
        </div>
        <table class="table table-condensed table-hover">
            <tbody>
              <% @options.each do |opt| %>
                    <tr class="<%= cycle('active', 'success', 'warning', 'danger', 'info')%>">
                    <td><i class="fa fa-hand-o-right" aria-hidden="true"></i></td>    
                     <td>
                       <%= "#{opt}" %>   
                     </td>
                    </tr>
              <% end %>
            </tbody>  
        </table>
     
    </div>
    
</div>

<div class = "row">
    <div class="col-md-8" <%= "id = q3bar" if @question.qid == 3 %>>
        <h1 class='text-primary'>Risposte</h1> <br/>
          
         <% if @question.qid == 3 %>
             <%= bar_chart(@count_drugs, colors: ["green", "#29970E"], library: {backgroundColor: "#eee", title: "Nome Farmaco", hAxis: {format: '0'}}) %>
            <%#= bar_chart(@count_drugs, colors: ["green", "#29970E"], library: {backgroundColor: "#eee", title: "Nome Farmaco", height: 1700,  bar: {groupWidth: "55%"}, chartArea: {height: '95%'}, vAxis: {textStyle:{color: 'red', fontSize: 10}}}) %>             
             <%= bar_chart(@count_categories, colors: ["purple", "#4C0E97  "], library: {backgroundColor: "#eee", title: "Categoria Farmacoterapeutica"}) %> 
            <%#= bar_chart(@count_categories, colors: ["purple", "#4C0E97  "], library: {backgroundColor: "#eee", title: "Categoria Farmacoterapeutica", height: 1700,  bar: {groupWidth: "55%"}, chartArea: {height: '95%'}, vAxis: {textStyle:{fontSize: 10}}}) %>             
        

        <% elsif @question.qid == 18 %>
            <table class="table table-condensed table-hover">
            <tbody>
               <tr>
                   <th></th>
                   <th>REMARKS</th>
               </tr><br/>
               <tr>
                   <th></th>
                   <th></th>
               </tr>               
              <% get_suggestions(@question.qid).each do |sugg| %>
                    <tr class="<%= cycle('active', 'success', 'warning', 'danger', 'info')%>">
                    <td><i class="fa fa-comments fa-2x" aria-hidden="true"></i></td>    
                     <td>
                       <%= "#{sugg}" %>   
                     </td>
                    </tr>
              <% end %>
            </tbody>  
        </table>        
        
         <% else %>
          <%# binding.pry %>
             
             <%= pie_chart(@counts, library: {sliceVisibilityThreshold: 1/1000}) %>
             <%# binding.pry %>
             <%= pie_chart(@counts, library: {sliceVisibilityThreshold: 1/1000, pieSliceText: 'value'}) %>
         <% end %>
    </div><br/>    
    
</div>

    <% @subquestions.each do |sq| %>
    <div class="col-md-8">
        <!--<#% binding.pry %>
        <%# puts "subqid: #{sq.subid}" %>
        <%# puts "subq_mapping: #{@subq_mapping[sq.subid]}" %> -->
        <h1 class="h1 question"><%="Sottodomanda #{@subq_mapping[sq.subid]}"%>

        </h1>
        <div class="well question-block subquestion-description">
            <h3>Descrizione</h3>
            <%= sq.qtext %>
        </div>
        
        <table class="table table-condensed table-hover">
            <tbody>
              <% @suboptions.each do |sopt| %>
                    <% if sopt.subid == sq.subid %>  
                        <tr class="<%= cycle('active', 'success', 'warning', 'danger', 'info')%>">
                        <td><i class="fa fa-hand-o-right" aria-hidden="true"></i></td>    
                         <td>
                           <%= "#{sopt.odescription}" %>   
                         </td>
                        </tr>
                    <% end %>    
              <% end %>
            </tbody>  
        </table>        
    </div>
    
    <div class = "row">
    <div class="col-md-8">
        <h1 class='text-primary'>Risposte</h1>
    
         <% if (@subquestion_idx.include? sq.qid)  && sq.subid == 1 %>
            <% count_drugs, count_categories = sub_count(sq.qid, sq.subid)[1..2] %>
            <%#= bar_chart(count_drugs, colors: ["green", "#29970E"], library: {backgroundColor: "#eee", title: "Nome Farmaco", height: 1700,  bar: {groupWidth: "55%"}, chartArea: {height: '95%'}, vAxis: {textStyle:{color: 'blue', fontSize: 10}}}) %>             
            <%= bar_chart(count_drugs, colors: ["green", "#29970E"], library: {backgroundColor: "#eee", title: "Nome Farmaco", hAxis: {format: '0'}, vAxis: {textStyle:{fontSize: 5}}}) %>
            <%= bar_chart(count_categories, colors: ["purple", "#4C0E97  "], library: {backgroundColor: "#eee", title: "Categoria Farmacoterapeutica", hAxis: {format: '0'}, vAxis: {textStyle:{fontSize: 5}}}) %>             
            <%#= bar_chart(count_categories, colors: ["purple", "#4C0E97  "], library: {backgroundColor: "#eee", title: "Categoria Farmacoterapeutica", height: 1700,  bar: {groupWidth: "55%"}, chartArea: {height: '95%'}, vAxis: {textStyle:{fontSize: 10}}}) %>         
         
         <% elsif sq.qid == 8%>
             <% count_prescriber, count_changer, count = get_prescriber(sq.qid, sq.subid) %>
             <%# binding.pry %>
             <%= column_chart(count_prescriber, colors: ["green", "#29970E"], library: {backgroundColor: "#eee", title: "Prescrittore della terapia"} ) %>
             <%= column_chart(count_changer, colors: ["purple", "#4C0E97  "], library: {backgroundColor: "#eee", title: "Modificatore della terapia"}) %>
             <%= bar_chart(count, colors: ["orange"], library: {backgroundColor: "#eee", title: "Prescrittore e Modificatore della terapia"})%>
         <% else %>
             <% counts = sub_count(sq.qid, sq.subid)[0] %>
             <%# binding.pry %>
             <% if counts.keys.length < 3 %>
                 <%= pie_chart(counts) %>
             <% else %>
                 <%= column_chart(counts,  colors: ["lightcoral", "#F08080"], library: {backgroundColor: "#eee"}) %>
            <% end %>
        <% end %>  

    </div><br/>    
    
    </div>
    
    
    <% end %>


     