config/routes.rb
Rails.application.routes.draw do
  
  

  
  get 'advices/leave'
  get 'advices/statistics', to: 'advices#advice_statistics'
  get 'intro', to: 'advices#intro'
  resources :advices
  
  get 'advices/first'
  get 'advices/second'

  resources :surveys
  resources :patients do 
    resource :profile
  end  

  
  devise_for :members, :controllers => {:registrations => "members"}
  resources :members 
  
  get 'questions/index'
  

  

  get 'users/index'

  get 'questions/notes'
  
  get 'statistics/list_indicator'
  get 'statistics/adverse_reactions'
  get 'statistics/side_effects'
  get 'statistics/drugs'
  get 'statistics/aggregated_drugs'
  post 'statistics/aggregated_drugs'
  
  resources :users
  resources :questions
  
  resources :statistics

  get 'pages/home'
  root 'pages#home'  

end

app/models/patient.rb
class Patient < ActiveRecord::Base
    has_one :profile
end

app/controllers/patients_controller.rb
require 'securerandom'

class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
    
    @collection_points = ["Farmacia", "Poliambulatorio medico", "Ospedale"]
    @random_id = nil
    patient_ids = Patient.all.map{|p| p.patient_id}
    
    while true do
      @random_id = SecureRandom.hex(5).upcase
      break unless patient_ids.include? @random_id
    end  
    
    
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
       params.require(:patient).permit(:patient_id, :collection_point, :collection_point_name, :collection_point_address)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
    <% if @patient.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>
  
        <ul>
        <% @patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field form-group">
        <%= f.label :patient_id, "id paziente".upcase %><br/>
        <%= f.text_field :patient_id, autofocus: true, value: @random_id, class: 'form-control' %>
    </div><br/>
    
     <div class="field form-group">
        <%= f.label "tipologia luogo di raccolta" %><br/>
        <%= f.select :collection_point, @collection_points, class: 'form-control', include_blank: true %>
    </div><br/>
    
    <div class="field form-group">
        <%= f.label "luogo di raccolta"%><br/>
        <%= f.text_field :collection_point_name, autofocus: true, class: 'form-control' %>
    </div><br/>
    
    <div class="field form-group">
        <%= f.label "indirizzo luogo di raccolta"%><br/>
        <%= f.text_field :collection_point_address, autofocus: true, class: 'form-control' %>
    </div><br/>

  <div class="actions form-group">
    <%= f.submit "Registra", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>
      <p id="notice"><%= notice %></p>
      
      <h1><span class="homeh1color1">L</span>isting <span class="homeh1color1">P</span>atients</h1><br/>
      
      <table class="patient table table-bordered table-hover">
        <thead>
          <tr>
            <th><%= "ID PAZIENTE" %></th>
            <th><%= "Punto di Raccolta" %></th>
            <th><%= "Tipologia Punto di Raccolta" %></th>
            <th class='icon'><i class="fa fa-eye fa-lg" aria-hidden="true"></i></th>
            <th class='icon'><i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i></th>
            <th class='icon'><i class="fa fa-eraser fa-lg" aria-hidden="true"></i></th>      
          </tr>
        </thead>
      
        <tbody>
          <% @patients.each do |patient| %>
            <tr>
              <td><%= patient.patient_id %></td>
              <td><%= patient.collection_point_name %></td>
              <td><%= patient.collection_point%></td>
              <td><%= link_to 'Show', patient %></td>
              <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
              <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

  </div>
</div>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="well">
            <h2>New Patient</h2><br/>
            <%= render 'form' %>
        </div>
    </div>
</div>    
<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<div class="row">
    
    <p id="notice"><%= notice %></p>
    <div class="col-md-3 text-center">    
        <%#= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %><br/>
    </div>

    <div class="col-md-6">
        <p><%= @patient.patient_id %></p>
        <p><%= @patient.collection_point %></p>
        <p><%= @patient.collection_point_name %></p>
        <p><%= @patient.collection_point_address %></p>        
    </div>
</div>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>