config/routes.rb
Rails.application.routes.draw do
  
  

  
  get 'advices/leave'
  get 'advices/statistics', to: 'advices#advice_statistics'
  get 'intro', to: 'advices#intro'
  resources :advices
  
  get 'advices/first'
  get 'advices/second'

  resources :surveys
  resources :patients do 
    resource :profile
  end  

  
  devise_for :members, :controllers => {:registrations => "members"}
  resources :members 
  
  get 'questions/index'
  

  

  get 'users/index'

  get 'questions/notes'
  
  get 'statistics/list_indicator'
  get 'statistics/adverse_reactions'
  get 'statistics/side_effects'
  get 'statistics/drugs'
  get 'statistics/aggregated_drugs'
  post 'statistics/aggregated_drugs'
  
  resources :users
  resources :questions
  
  resources :statistics

  get 'pages/home'
  root 'pages#home'  

end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  include AdvicesHelper
  skip_before_action :authenticate_member!, except: [:advice_statistics, :index, :show]
  before_action :set_advice, only: [:show, :edit, :update, :destroy], except: [:intro]
  

  # GET /advices
  # GET /advices.json
  def index
     @advice_details = AdviceDetail.all.paginate(:page => params[:page], :per_page => 3)
     #@advices = Advice.all. paginate(:page => params[:page], :per_page => 3).order('id ASC')
  end
  
  def intro
    @selection = "health system"
    redirect_to new_advice_path(:selection => "health system")
  end  

  # GET /advices/1
  # GET /advices/1.json
  def show
    @advice = Advice.find(params[:id])
    @advice_details = AdviceDetail.find_by_aid(@advice.id)
  end

  # GET /advices/new
  def new
    @selection = get_choice(params[:selection])
    session[:choice] = params[:selection]
    session[:color_selection] = @selection unless @selection.empty?
    logger.info "selection inside new: #{session[:color_selection]}"
    session[:advice_params] ||= {}
    @advice = Advice.new(session[:advice_params])
    @advice.current_step = session[:advice_step]
    #@advice = Advice.new
  end

  # GET /advices/1/edit
  def edit
  end

  # POST /advices
  # POST /advices.json
  def create
    session[:advice_params].deep_merge!(params[:advice]) if params[:advice]
    self.set_session
    
    logger.info "color_selection inside create: #{session[:color_selection]}"
    logger.info "session[:advice01] = #{session[:advice01]}"
    logger.info "choice inside create: #{session[:choice]}"
    
   
    @default_keywords = get_defualt_keywords(session)
    @selected_topics = get_topics_selected(session)
    td_objs = create_topic_description_objects(100, "problema", @selected_topics, session)
     
    
    @advice = Advice.new(session[:advice_params])
    @advice.current_step = session[:advice_step]

    if params[:back_button]
        @advice.previous_step
    elsif @advice.last_step?
        ActiveRecord::Base.transaction do
           @advice.save
           
           aid = @advice.id
           logger.debug "aid: #{aid}"
           advice_details = create_advice_details(aid, session)
           logger.debug "advice_details: #{advice_details.inspect}"
           advice_details.save
           topic_description_objs = create_topic_description_objects(aid, advice_details.typology, @selected_topics, session)
           topic_description_objs.each do |td|
             td.save
           end   
           session_cleaner
        end
      
    else 
      @advice.next_step
    end
    session[:advice_step] = @advice.current_step    
    if @advice.new_record?
      # session.keys().each do |k|
      #   logger.info "#{k}: #{session[k]}"
      # end  
      render "new", color_selection: session[:color_selection]
      
    else
      session[:advice_step] = session[:advice_params] = nil
      flash[:success] = "Grazie della collaborazione!"
      redirect_to root_path(:step => "final_step")
      #redirect_to @survey
    end  

    #@advice = Advice.new(advice_params)

    # respond_to do |format|
    #   if @advice.save
    #     format.html { redirect_to @advice, notice: 'Advice was successfully created.' }
    #     format.json { render :show, status: :created, location: @advice }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @advice.errors, status: :unprocessable_entity }
    #   end
    # end
  end
  
  def set_session
    session[:color_selection] = params[:color_selection] if params[:color_selection]
    session[:choice] = params[:selection] if params[:selection]
    session[:advice01] = params[:advice01] if params[:advice01]
    session[:advice02] = params[:advice02] if params[:advice02]
    session[:advice03_a] = params[:advice03_a] if params[:advice03_a] #Ospedale
    session[:advice03_b] = params[:advice03_b] if params[:advice03_b] #Farmacia
    session[:advice03_c] = params[:advice03_c] if params[:advice03_c] #Poliambulatorio
    session[:advice03_d] = params[:advice03_d] if params[:advice03_d]#Ambulatorio medico
    session[:advice03_e] = params[:advice03_e] if params[:advice03_e]
    session[:advice03_f] = params[:advice03_f] if params[:advice03_f]
    #session[:advice03] = params[:advice03] if params[:advice03] #provincia selezionata
    session[:advice04_a] = params[:advice04_a] if params[:advice04_a] #Distribuzione presidi medici
    session[:advice04_b] = params[:advice04_b] if params[:advice04_b] #Sistemi di prenotazione
    session[:advice04_c] = params[:advice04_c] if params[:advice04_c] #Distribuzione di farmaci
    session[:advice04_d] = params[:advice04_d] if params[:advice04_d] #Campagne di vaccinazione  
    session[:advice04_e] = params[:advice04_e] if params[:advice04_e] #Altro 

    session[:advice05_a_0] = params[:advice05_a_0] if params[:advice05_a_0] # Farmaci inefficacia
    session[:advice05_b_0] = params[:advice05_b_0] if params[:advice05_b_0] #Distribuzione presidi medici
    session[:advice05_c_0] = params[:advice05_c_0] if params[:advice05_c_0] #Sistemi di prenotazione
    session[:advice05_d_0] = params[:advice05_d_0] if params[:advice05_d_0] #Distribuzione di farmaci
    session[:advice05_e_0] = params[:advice05_e_0] if params[:advice05_e_0] # Farmaci Inequivalenza
    
    session[:advice05_a_1] = params[:advice05_a_1] if params[:advice05_a_1] #Distribuzione presidi medici
    session[:advice05_b_1] = params[:advice05_b_1] if params[:advice05_b_1] #Sistemi di prenotazione
    session[:advice05_c_1] = params[:advice05_c_1] if params[:advice05_c_1] #Distribuzione di farmaci
    session[:advice05_d_1] = params[:advice05_d_1] if params[:advice05_d_1] # Farmaci Inequivalenza
    session[:advice05_e_1] = params[:advice05_e_1] if params[:advice05_e_1] # Farmaci inefficacia
    
    session[:advice05_a_2] = params[:advice05_a_2] if params[:advice05_a_2] #Distribuzione presidi medici
    session[:advice05_b_2] = params[:advice05_b_2] if params[:advice05_b_2] #Sistemi di prenotazione
    session[:advice05_c_2] = params[:advice05_c_2] if params[:advice05_c_2] #Distribuzione di farmaci
    session[:advice05_d_2] = params[:advice05_d_2] if params[:advice05_d_2] # Farmaci Inequivalenza
    session[:advice05_e_2] = params[:advice05_e_2] if params[:advice05_e_2] # Farmaci inefficacia
    
    session[:advice05_a_3] = params[:advice05_a_3] if params[:advice05_a_3] #Distribuzione presidi medici
    session[:advice05_b_3] = params[:advice05_b_3] if params[:advice05_b_3] #Sistemi di prenotazione
    session[:advice05_c_3] = params[:advice05_c_3] if params[:advice05_c_3] #Distribuzione di farmaci
    session[:advice05_d_3] = params[:advice05_d_3] if params[:advice05_d_3] # Farmaci Inequivalenza
    session[:advice05_e_3] = params[:advice05_e_3] if params[:advice05_e_3] # Farmaci inefficacia
    
    session[:advice05_a_4] = params[:advice05_a_4] if params[:advice05_a_4] #Distribuzione presidi medici
    session[:advice05_b_4] = params[:advice05_b_4] if params[:advice05_b_4] #Sistemi di prenotazione
    session[:advice05_c_4] = params[:advice05_c_4] if params[:advice05_c_4] #Distribuzione di farmaci
    session[:advice05_d_4] = params[:advice05_d_4] if params[:advice05_d_4] # Farmaci Inequivalenza
    session[:advice05_e_4] = params[:advice05_e_4] if params[:advice05_e_4] # Farmaci inefficacia
    session[:keyword] = params[:keyword] if params[:keyword]
  end
  
  
  def advice_statistics
    @advice_details = AdviceDetail.all
    ### Advice Statics ####
    ### Ambito - farmaci, sistema sanitario, farmaci acquistati su internet
    @choice_alternatives = AdviceDetail.all.uniq.pluck(:choice)
    @choices = AdviceDetail.all.group(:choice).count(:choice)
    @choices = change_key_case(@choices)
    # choices = {}
    # @choices.map{|k, v| choices[k.capitalize] = v}
    # @choices = choices
    ### Tipolagia di segnalazione
    @typologies = AdviceDetail.all.group(:typology).count(:typology)
    @typologies = change_key_case(@typologies)
    ## Strutture segnalate ##
    ### businsess logic moved to the view
    # @places = AdviceDetail.all.pluck(:place)
    # @places = count_elements(@places)
    # @places = change_key_case(@places)
    #@places_by_province = get_place_by_province()
    ### Oggetto Segnalazioni ###
    # @topics = count_elements(AdviceDetail.all.pluck(:topic))
    # @topics = change_key_case(@topics)
    ### Problematiche ###
    # problems = AdviceDetail.where(typology: "problema").pluck(:description)
    # problems = count_elements(problems)
    # @problems = change_key_case(problems)
    
    ## Suggerimenti ###
    # suggestions = AdviceDetail.where(typology: "esigenza/suggerimento").pluck(:description)
    # suggestions = count_elements(suggestions)
    # @suggestions = change_key_case(suggestions)
    occurrences1 = AdviceDetail.where(:choice => "farmaci").group(:keyword).count
    @chart1 = generate_bubble(occurrences1)
    
    occurrences2 = AdviceDetail.where(:choice => "farmaci acquistati su internet").group(:keyword).count
    @chart2 = generate_bubble(occurrences2)
    
    #occurrences3 = AdviceDetail.where(:choice => "sistema sanitario").group(:keyword).count
    keywords = AdviceDetail.where(:choice => "sistema sanitario").pluck(:keyword)
   
    logger.info "keywords: #{keywords}"
    occurrences3 = count_elements(keywords)
    logger.info "keyword occurences: #{occurrences3}"
    @chart3 = generate_bubble(occurrences3)
    
  
  end  
  

  # PATCH/PUT /advices/1
  # PATCH/PUT /advices/1.json
  def update
    respond_to do |format|
      if @advice.update(advice_params)
        format.html { redirect_to @advice, notice: 'Advice was successfully updated.' }
        format.json { render :show, status: :ok, location: @advice }
      else
        format.html { render :edit }
        format.json { render json: @advice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advices/1
  # DELETE /advices/1.json
  def destroy

app/helpers/advices_helper.rb
module AdvicesHelper
    
def session_cleaner
    advice_keys = session.keys.select{|key| key.to_s.match(/^advice*/)}
    advice_keys.each do |key|
        session.delete(key)
    end    
end

def get_choice(choice)
    res = "danger"
    if choice == "drugs"
        res = "primary"
    elsif choice == "health system"
        res = "warning"
    elsif choice == "shopping"
        res = "success"
    else    
        res = "danger"
    end
    res
end


def extract_choice(choice)
    if choice == "drugs"
        res = "farmaci"
    elsif choice == "health system"
        res = "sistema sanitario"
    elsif choice == "shopping"
        res = "farmaci acquistati su internet"
    else
        res = "scelta non effettuata"
    end
    res
end    

def create_advice_details(advice_id, session)
    advice_details = AdviceDetail.new
    places = []
    topics = []
    descriptions = []
    aid = advice_id
    ### building of the advice details object ##
    advice_details.aid = aid
    
    session.keys().each do |k|
        if k == "choice"
            advice_details.choice = extract_choice(session[k])
        end
        
        if k == "advice01"
            advice_details.typology = session[k].downcase
        end
        if k == "advice02"
            advice_details.province = session[k]
        end
        if k  =~ /advice03_/
           places.append(session[k].downcase)
        end
        if k  =~ /advice04_/
            topics.append(session[k].downcase)
        end
        if k  =~ /advice05_/
            descriptions.append(session[k].downcase)
        end
        if k == "keyword"
            advice_details.keyword = session[k].downcase
        end            
            
    end
    places = places.reject { |e| e.to_s.empty? }
    topics = topics.reject {|e| e.to_s.empty?}
    descriptions = descriptions.reject {|e| e.to_s.empty?}
    advice_details.place = places.join(", ")
    advice_details.topic = topics.join(", ")
    advice_details.description = descriptions.join(", ")
    
    return advice_details

end

def change_key_case(dictionary)
    new_dict =  {}
    dictionary.map do |k, v|
        unless k.nil?
            new_dict[k.capitalize] = v
        end
    end    
    return new_dict
end

def count_elements(original_list)
    elements = []
    counts = Hash.new(0)
    original_list.each do |p|
        elements.append(p.split(", "))
        #elements.append(p)
    end
    pp = elements.flatten()
    
    pp.each{|e| counts[e] += 1}
    counts
    counts = change_key_case(counts)
    counts
end

def get_places_by_choice(choice)
    places = AdviceDetail.where(:choice => choice).pluck(:place)
    places = count_elements(places)
    places = change_key_case(places)
    places
end    


def get_place_by_province(choice)
    provinces = AdviceDetail.where(:choice => choice).distinct.pluck(:province)
    stacked_data = []
    provinces.each do |p|
       place_list = AdviceDetail.where(province: p, choice: choice).pluck(:place)
       places = count_elements(place_list)
       d = {:name => p, :data => places.map{|k, v| [k.capitalize, v]}}
       stacked_data.append(d)
    end 
    stacked_data
end

def create_topic_description_objects(aid, typology, selected_topics, session)
    topic_description_objs = []
    selected_topics.each_with_index do |t, idx|
       topic = t
       descriptions = ['a','b','c','d','e'].map do |l|
           session["advice05_#{l}_#{idx}".to_sym]
       end
       descriptions = descriptions.reject(&:blank?)
       descriptions = descriptions.join(', ')
       td = TopicDescription.new(aid: aid, typology: typology, topic: topic, description: descriptions)
       topic_description_objs << td
    end
    topic_description_objs
end

### the method provides the reportings (topics) and the related problems or advices. It correlates a particular reporting to the different problems or advices (description)
def get_topic_by_description(typology)
    #reportings = AdviceDetail.where(:typology => typology).distinct.pluck(:topic)
    reportings = TopicDescription.where(:typology => typology).distinct.pluck(:topic)
    
    stacked_data = []
    reportings.each do |r|
        description_list = TopicDescription.where(topic: r, typology: typology).pluck(:description)
        logger.info "Description List: #{description_list}"
        descriptions = count_elements(description_list)
        logger.info "*** descriptions: #{descriptions}"
        d = {:name => r, :data => descriptions.map{|k,v| [k.capitalize, v]}}
        stacked_data.append(d)
    end
    stacked_data
end

def get_topics_selected(session)
    topics_selected = []
    session.keys.each do |k|
        if k =~ /advice04_[abcdef]/ and session[k] != ""
           topics_selected << session[k]
        end
    end
    topics_selected
end
    
        
    


def create_bubble_series(keyword_occurences)
    bubble_series = []
    xmax = keyword_occurences.keys.length 
    ymax = keyword_occurences.values.max
    logger.info "ymax: #{ymax}"
    
    tot = keyword_occurences.values.sum
    bubble_series = keyword_occurences.map do |k,v|
        
        percentage = 100*(v.to_f/tot).round(3)
        {x: rand(xmax + 5), y: v, z: v, keyword: k, percentuale: percentage}

    end
    #binding.pry
    bubble_series
    
end    

def generate_bubble(occurrences)
   #bubble_series = [{x: 1, y: 2, z: 3}, {x: 4, y: 5, z: 6}]
   bubble_series = create_bubble_series(occurrences)
   logger.info "bubble_series: #{bubble_series}"
   mychart = LazyHighCharts::HighChart.new('bubble') do |f|
          f.title(text: 'Distribuzione delle keywords individuate')            
          f.chart(type: 'bubble', zoomType: 'xy', plotBorderWidth: 1) 
          f.xAxis [title: {text: 'Keywords'}]
          f.yAxis [title: {text: 'Occorrenze' }]
          f.tooltip({
                useHTML: true,
                headerFormat: '<table>',
                pointFormat: '<tr><th colspan="2"><h3>{point.country}</h3></th></tr>' +
                    '<tr><th>Keyword:</th><td>{point.keyword}</td></tr>' +
                    '<tr><th>Occorrenze:</th><td>{point.z}</td></tr>' +
                    '<tr><th>Percentuale:</th><td>{point.percentuale}%</td></tr>',
                footerFormat: '</table>',
                followPointer: true
          })
          f.series(
            data: bubble_series,
            marker: {
              fillColor: {
                radialGradient: { cx: 0.4, cy: 0.3, r: 0.7 },
                stops: [ [0, 'rgba(255,255,255,0.5)'], [1, 'rgba(69,114,167,0.5)'] ]
             }
           }
         )
    end
    mychart
end 



def get_defualt_keywords(session)
    default_keywords = []
    session.keys.each do |k|
        if k =~ /advice03_[abcdef]/ and session[k] != ""
            default_keywords << session[k]
            
        end
    end
    default_keywords.join(', ')
end    
    
end    

app/views/advices/_a1.html.erb
<div class="row">
  <div class="panel panel-<%=session[:color_selection]%>">
    <div class="panel-heading"><%= "STEP #{@advice.current_step_idx(@advice.current_step)}" %></div>
    <div class="panel-body" align="center">
      <!--<h2>Di cosa si tratta?</h2> -->
      <h2>È un suggerimento o un possibile problema?</h2>
    </div>
</div>


<div class="advice_intro">
<fieldset class="<%= session[:color_selection] + '_choice'%>">
    <div class="radio">
      <label><input type="radio" name="advice01" value="Problema" <%= 'checked' if session[:advice01] == "Problema" %> >Problema</label><br/>
      <label><input type="radio" name="advice01" value= "Suggerimento" <%= 'checked' if session[:advice01] == "Suggerimento" %>>Suggerimento</label>
    </div>
</fieldset>
</div>
 
 <%#= debug(session[:choice]) %>

app/views/advices/_a2.html.erb
<div class="row">
  <div class="panel panel-<%=session[:color_selection]%>">
    <div class="panel-heading"><%= "STEP #{@advice.current_step_idx(@advice.current_step)}" %></div>
    <div class="panel-body" align="center"><h2>Provincia</h2></div>
</div>
</div>
<div class="row">
 <div class="container">
  <% text_message = session[:choice] == "shopping" ? " ti trovi" : " è situata la struttura segnalata in precedenza" %>     
  <!--<p>Indicare la provincia in cui <%#= text_message%></p> -->

<% options = ["", "Città metropolitana di Cagliari", "Sud Sardegna", "Nuoro", "Oristano", "Sassari"] %>
<%= select_tag "advice02", options_for_select(options, session[:advice02]), multiple: false, class: "selectpicker" %><br/><br/>

</div>

</div> 
 
 <%#= debug(session[:choice]) %>
 <%#= debug(params[:advice02]) %>

app/views/advices/_confirmation.html.erb
<%#= javascript_include_tag 'char_limit' %>
<%# session.keys().each do |k, v|%>
    <%#= "#{k}: #{session[k]}" %> <br/>
<%# end %>    
<div class="row">
  <div class="panel panel-<%=session[:color_selection]%>">
    <div class="panel-heading">FINE</div>
    <div class="panel-body" align="center"><h2>Keywords <%#= session[:advice01] == "Problema" ? "problema" : "suggerimento o l'esigenza" %></h2></div>
</div>
</div>
<div class="row">
 <div class="container">
 <!-- <p>Indicare un termine (al singolare) che descriva il <%#= session[:advice01] == "Problema" ? "problema" : "suggerimento o l'esigenza" %></p>-->
  <div class="row">
    <div class="col-md-6">
        <!--<form>-->
            <%= text_area_tag 'keyword', @default_keywords, class: 'form-control', placeholder: "keyword", maxlength: 100, rows: 3, cols: 25 %>
            <!--<strong><span id="rchars">10</span></strong> caratteri rimanenti-->           
        <!--</form> -->

       <!--<textarea class="form-control" rows="3" placeholder="keyword" name="answer18_note" ></textarea> -->
    </div>
</div>

 
</div>

</div> 
 
  <%#= debug params %>

app/views/advices/_form.html.erb
<%#= params.inspect %>
<%= form_for(@advice, :html => {class: "form-group"}, :color_selection => @selection) do |f| %>
  <% if @advice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@advice.errors.count, "error") %> prohibited this advice from being saved:</h2>

      <ul>
      <% @advice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="jumbotron">
  <!--<div class="container">-->
 
    <ul class="pagination">
          <% unless @advice.first_step?%>
              <%= button_tag(type: "submit", :id => "back_cmd", :name => "back_button", class: "btn btn-lg btn-primary") do %>
                  <i class="fa fa-arrow-circle-left"></i><br/>
              <% end %>
          <% end %> 
          <% unless @advice.last_step? %>
              <%#= link_to "Exit", advices_leave_path %>
              <%= link_to advices_leave_path, id: "advice_arrow", class: "btn btn-lg btn-danger active" do %>
                  <i class="fas fa-sign-out-alt"> Esci</i><br/>
              <% end %>
              <%= button_tag(type: "submit", class: "btn btn-lg btn-primary") do %>
                  <i class="fa fa-arrow-circle-right"></i><br/>
              <% end %>

          <% else %>
              <%= link_to advices_leave_path, id: "advice_arrow", class: "btn btn-lg btn-danger active" do %>
                  <i class="fas fa-sign-out-alt"> Esci</i><br/>
              <% end %>          
              <%= button_tag(type: "submit", class: "btn btn-lg btn-success") do %>
                  <i class="fas fa-share-square">  Invia</i><br/>
              <% end %>
          <% end %>
      </ul>

    <%= render "#{@advice.current_step}", :f => f, :color_selection => @selection %>    
  <!--</div><br/> -->
</div>

<% end %>

 

app/views/advices/edit.html.erb
<h1>Editing Advice</h1>

<%= render 'form' %>

<%= link_to 'Show', @advice %> |
<%= link_to 'Back', advices_path %>

app/views/advices/index.html.erb
<div class=well>
    <div class="digg_pagination"%>
        <!--<div class="page_info">
            <%#= page_entries_info @advice_details %>    
        </div> -->
        <%=will_paginate @advice_details, :container => false %>
    </div>
</div>


<div class='row'>
  <div class='col-md-10 col-md-offset-1'>
        <p id="notice"><%= notice %></p>
        <h1 class='advices'><span class="homeh1color1">E</span>lenco <span class="homeh1color1">S</span>uggerimenti - <span class="homeh1color1">P</span>roblematiche</h1>
      
                  
        <%# end %>
        <table class="advices table table-bordered table-hover">
          <thead>
            <tr>
              <th>Codice</th>
              <th>Tipologia</th>
              <th>Ambito</th>
              <!--<th></th> -->
              <th class='icon'><i class="fa fa-eye fa-lg" aria-hidden="true"></i></th> 
              <!--<th class='icon'><i class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></i></th> -->
              <th class='icon'><i class="fa fa-eraser fa-lg" aria-hidden="true"></i></th>
            </tr>
          </thead>
        
          <tbody>
            <% @advice_details.each do |ad| %>
              <tr>
                <!--<td><%#= survey.card %></td> -->
                <td><%= ad.aid %></td>
                <td><%= ad.typology%></td>
                <td><%= ad.choice%></td>
                <td><%= link_to 'Show', advice_path(ad) %></td>
                <!--<td><%#= link_to 'Edit', edit_advice_path(ad) %></td> -->
                <td><%= link_to 'Rimuovi', @advice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>
<br>



<!--<p id="notice"><%#= notice %></p>

<h1>Listing Advices</h1>

<table>
  <thead>
    <tr>
      <th>Uid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @advices.each do |advice| %>
      <tr>
        <td><%#= advice.uid %></td>
        <td><%#= link_to 'Show', advice %></td>
        <td><%#= link_to 'Edit', edit_advice_path(advice) %></td>
        <td><#%= link_to 'Destroy', advice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Advice', new_advice_path %>

app/views/advices/new.html.erb
<%= render 'form' %>

app/views/advices/show.html.erb
    
    <p id="notice"><%= notice %></p>
   
    <div class="container">
        <h1 class='advices'><span class="homeh1color1">T</span>ipologia: <span class="homeh1color1"><%=@advice_details.typology[0].upcase unless @advice_details.typology.nil? %></span><%=@advice_details.typology[1, @advice_details.typology.length] unless @advice_details.typology.nil? %>
         <%= link_to advices_path, id: "list_button", class: "btn btn-lg btn-danger active" do %>
                      <i class="fas fa-bars">  Torna all'elenco</i><br/>
        <% end %>
        </h1>
        </div>
        <br/>
        <div class="container">
           
          <% @advice_details.attributes.each do |k, v| %>
             
                <% case k 
                when "choice" %><% k = "ambito" %>
                <% when "place" %> <% k = "struttura" %>
                <% when "province" %> <% k = "provincia" %>
                <% when "topic" %> <% k = "argomento" %>
                <% when "description" %> <% k = "descrizione" %>
                <% when "keyword" %> <% k  = "keyword" %>
                <% else %>
                    <% next %>
                <% end %>
                <div class="well">
                    <div class="row">
                        <div class="col-md"></div><p class="col-md-2"><strong><%=k.upcase%></strong>:</p><p class="col-md-6"><%=v %></p>
                    </div>
                </div>  
            <% end %>
                
              </div>    
          
        </div>
 </div>

    

   