config/routes.rb
Rails.application.routes.draw do
  
  

  
  get 'advices/leave'
  get 'advices/statistics', to: 'advices#advice_statistics'
  get 'intro', to: 'advices#intro'
  resources :advices
  
  get 'advices/first'
  get 'advices/second'

  resources :surveys
  resources :patients do 
    resource :profile
  end  

  
  devise_for :members, :controllers => {:registrations => "members"}
  resources :members 
  
  get 'questions/index'
  

  

  get 'users/index'

  get 'questions/notes'
  
  get 'statistics/list_indicator'
  get 'statistics/adverse_reactions'
  get 'statistics/side_effects'
  get 'statistics/drugs'
  get 'statistics/aggregated_drugs'
  post 'statistics/aggregated_drugs'
  
  resources :users
  resources :questions
  
  resources :statistics

  get 'pages/home'
  root 'pages#home'  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Punto Collabora</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%#= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" %>

  <%#= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= javascript_include_tag "https://code.highcharts.com/highcharts.js" %>
  <%= javascript_include_tag "https://code.highcharts.com/highcharts-more.js" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" %>
  
  <!-- Latest compiled and minified CSS -->

<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/css/bootstrap-select.min.css">

<!-- Latest compiled and minified JavaScript -->

<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/bootstrap-select.min.js"></script> 

<!-- (Optional) Latest compiled and minified JavaScript translation files -->

<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.5/js/i18n/defaults-*.min.js"></script>

<!-- Awesome Fonts -->
 <script src="https://kit.fontawesome.com/23eb448860.js"></script>
  
  <%= csrf_meta_tags %>
  
</head>

<%#= debug params %>
<body>
<div class="navbar navbar-inverse navbar-static-top">

     <div class="container">
        <% if current_member %>
            <%= link_to root_path, class: 'navbar-brand' do %>
                <!--<i class="fa fa-flask" ></i>-->
                  
                  <i class="fas fa-handshake"></i>     
                  PUNTO COLLABORA COVID 19<!--<strong>+</strong> -->
              <% end %> 
         <% end %> 
          <!--<a href="#" class="navbar-brand">COLLABORAFARMACISOLA</a>-->
          <button class="navbar-toggle" data-toggle = "collapse" data-target =".navHeaderCollapse">
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>
            <span class='icon-bar'></span>            
          </button>
          <div class="collapse navbar-collapse navHeaderCollapse">
              <div class="nav navbar-nav navbar-right">
                  <% if current_member %>
                      <%= button_to 'Sign Out', destroy_member_session_path, method: :delete, class: 'btn btn-primary navbar-btn'%>
                  <% else %>
                       <!-- to replace in a second phase 
                      <%#= link_to 'Area Riservata', new_member_session_path, class: "btn btn-danger navbar-btn active", method: :get %> -->
                  <% end %>      
              </div>
              
                
 
                <ul class="nav navbar-nav navbar-right">
                <!--<li class="active"><a href="#">MENU</a></li> -->
                
                <li class="dropdown active">
                 <% if current_member && (current_member.email == Member.first.email || current_member.email == Member.find_by_id(3).email)%>    
                  <a id="menu" href="/pages/home" class="dropdown" data-toggle="dropdown">Menu</a>          
                       <ul class="dropdown-menu">
                         <!--<li><%#=link_to "Dati Raccolti", advices_path %></li> -->
                         <li><%= link_to "Analisi dei Risultati", advices_statistics_path %></li>
                  <% end %>         
                         <% if current_member && (current_member.email == Member.first.email) %>
                             <li><%=link_to "Registrazione Utenti", new_member_registration_path %></li>
                             <li><%= link_to "Modifica Utenti", edit_member_registration_path %></li>
                         <% end %>      
                       </ul>
                    </li>
                 </ul>
                <%# end %> 
          </div>
     </div>  

</div>
      <div class="container">
        <!--<div class="alert alert-danger" role="alert"><%#= alert unless alert.nil? %></div>
        <div class="alert alert-info" role="alert"><%#= notice unless notice.nil? %></div> -->
          <% flash.each do |key, value| %>
                  <div id="<%= "thank_you" if params[:step] == 'final_step' %>" class="<%= flash_class(key.to_sym) %>">
                        <%= value %>
                  </div>
          <% end %>
          <%= yield %>  
    </div>
    <!--<div><%#= current_member %></div> -->
<% if current_member %>
    <%= render partial: "footer" %>
<% end %>    
</body>

</html>